### PR TITLE
Chunk references

### LINKED ISSUE #2: Display of chunks that are embedded within a chunk
knitr allows code chunks to be nested within each other, as explained [here](https://bookdown.org/yihui/rmarkdown-cookbook/reuse-chunks.html).  However, when the file is knitted, the output one sees does not show the label of the code chunk but instead replaces it with the actual code.  Compare this to how literate programming output is displayed in [Knuth's literate programming paper](http://www.literateprogramming.com/knuthweb.pdf).  In the context of `litr`, it seems we'd like to see the label of the inner code chunk rather than the code of the inner code chunk. If a Rmd file has nested code chunks, we'd like the following behavior:

1. The actual code that is run should still behave exactly as it does normally in knitr.
2. If a code chunk has something of the form `<<inner-chunk>>` within it, we should see `<<inner-chunk>>` with a hyperlink.  The hyperlink would take you to the code chunk with label `"inner-chunk"`.  It would also be nice for that code chunk to have its label visible (perhaps in small letters and in parentheses in a way that it is not mistaken for the code itself).

### PR DESCRIPTION
**Pull request by patrickvossler18**
Closes #2.

### CODE REVIEW

**Comment by jacobbien** [comment]
This isn't quite working how I would have hoped for two reasons:

1. For some reason RStudio still tries to open the file.  I wonder if this means we need to do the tryCatch directly around `rmarkdown::render()`... and then continue to pass that outward.  (I.e., leave the try-catch you have, but add an additional one directly around `rmarkdown::render()`.

Screen Shot 2022-07-20 at 4 32 01 PM

2. If I click on the "Issues" tab, the error references lines relative to the _TMP file rather than the original one...
```
Quitting from lines 83-88 (create-rhello_TMP.Rmd) 
Error in eval(expr, envir, enclos) : Whoa!
Calls: local ... withVisible -> eval_with_user_handlers -> eval -> eval
Execution halted
Error: Failed to run 'render_' in a new R session.
Execution halted
```
This is a problem that I guess we could have foreseen.  This does seem to be a problem with the current approach of running rmarkdown::render() on the _TMP file.

**Comment by jacobbien** [comment]
Here's the example I was running it on.

[create-rhello.Rmd.zip](https://github.com/jacobbien/litr-project/files/9155044/create-rhello.Rmd.zip)

**Comment by jacobbien** [comment]
I'm wondering about a different approach that doesn't use _TMP files at all.  The approach could be that you run the original Rmd file through `rmarkdown::render()` and then in post processing you replace the code that was added with the references.  Implementing this would require a lot of the same helper functions you've already written for finding reference chunks, labels, etc.

But before going down this path it'd be worth checking what the error messages look like when one has a reference label.  Is it with respect to the original Rmd file (my hope) or with respect to the version where the reference labels have been replaced with chunks?

**Comment by jacobbien** [comment]
> But before going down this path it'd be worth checking what the error messages look like when one has a reference label. Is it with respect to the original Rmd file (my hope) or with respect to the version where the reference labels have been replaced with chunks?

Ok I've confirmed that `rmarkdown::render()` gives the proper error message lines with reference chunks (i.e., the line numbers match what the user sees in the .Rmd file, not the line number with all the reference labels replaced with code.

So this means that I see no problems with the approach suggested in my previous comment.

**Comment by patrickvossler18** [comment]
[e1071b4](https://github.com/jacobbien/litr-project/pull/23/commits/e1071b4abc752c99ca01c2f679934fe2ccee5c57) is a lazy alternative in which we still create a backup file, but we make our changes on the original file and swap back in the backup file either once we've finished rendering or if there is an error while we are trying to render the file. With this approach, we avoid the issues tab problem and the missing file popup problem.

I consider this to be a lazy alternative because it avoids having to rewrite the functions to parse HTML output.

**Comment by jacobbien** [comment]
Unfortunately I don't think this really works as a solution.

- If you try running [this example](https://github.com/jacobbien/litr-project/files/9155044/create-rhello.Rmd.zip), it exits with a modified `create-rhello.Rmd` that has `@@@`'s in it.
- It also doesn't address the second problem (labeled "2") in [my comment earlier in the thread](https://github.com/jacobbien/litr-project/pull/23#issuecomment-1190874320).

**Comment by jacobbien** [comment]
To demonstrate what I mean... notice the error message says there was a problem in lines 83-88 but that was relative to the _TMP Rmd, not the one that the user knows about...
 
Screen Shot 2022-07-21 at 4 28 15 PM

**Comment by patrickvossler18** [comment]
Superseded by #24, closing.

**Pull request closed without merging**
